const db = require("../utils/database"); // this is a pool
const Cart = require("./cart");

module.exports = class Product {
  constructor(id, productTitle, imageUrl, description, price) {
    this.id = id;
    this.title = productTitle;
    this.imageUrl = imageUrl;
    this.description = description;
    this.price = price;
  }

  save() {
    return db.execute( // we don't specify id as it is auto generated by database engine
      "INSERT INTO products (title, imageUrl, description, price) VALUES (?, ?, ?, ?)",
      [this.title, this.imageUrl, this.description, this.price] // they will replace ? marks
    );
    // ?, ?, ?, ? is used to safely insert values and not face the issue of SQL injection (attack pattern)
    // mysql2 package безопасно экранирует наши input значения, чтобы проанализировать их на предмет скрытых команд SQL и удалить их
  }

  static fetchAll() {
    return db.execute("SELECT * FROM products"); // SELECT id, title FROM products => to select only id and title as a product object
  }

  static findById(id) { // * means all fields not all rows!!! WHERE is about rows and by default we get all rows
    return db.execute("SELECT * FROM products WHERE products.id = ?", [id]);
  }

  static deleteById(id) {
   
  }
}
